name: CI

on: [push,pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.4, 2.5, 2.6, 2.7, 3.0]
        os: [ubuntu, macos]
        experimental: [false]
    runs-on: ${{ matrix.os }}-latest
    continue-on-error: ${{ matrix.experimental }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: |
        gem install bundler -v 2.2.3
        bundle install
        bundle exec rake
